apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  name: ngsi-ld-city-device
  namespace: ktwin
spec:
  displayName: Device
  id: ngsi-ld-city-device
  properties:
  - name: dataProvider
    schema:
      primitiveType: string
    writable: true
  - name: dateModified
    schema:
      primitiveType: dateTime
    writable: true
  - name: dateCreated
    schema:
      primitiveType: dateTime
    writable: true
  - name: dateObserved
    schema:
      primitiveType: dateTime
    writable: true
  - name: source
    schema:
      primitiveType: string
    writable: true
  - description: level of the battery
    name: batteryLevel
    schema:
      primitiveType: string
    writable: true
  relationships:
  - maxMultiplicity: 1
    name: refDeviceModel
    interface: ngsi-ld-city-devicemodel
  service:
    autoScaling:
      maxScale: 1       # TODO 20 -> 1: for testing
      minScale: 1       # TODO: Ensure at least 1 pod is always running for testing, can be deleted when in production
      target: 1
      metric: "concurrency"
    template:
      spec:
        containers:
        - image: docker.io/fitzzzc/ktwin-device-service:0.1 # change to your image
          imagePullPolicy: IfNotPresent
          name: device
          resources: {}
status: {}
